name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - run: choco install dotnet4.7.2 --no-progress
    - run: dotnet restore
    - run: dotnet build --configuration Release --no-restore
    - run: dotnet test --verbosity normal --no-build
    - uses: gittools/actions/gitversion/setup@v2.0.1
      with:
        versionSpec: '6.x'
    - uses: gittools/actions/gitversion/execute@v2.0.1
      id: gitversion
      with:
        useConfigFile: true
    - run: dotnet pack --configuration Release --no-build /p:PackageVersion=${{ steps.gitversion.outputs.fullSemVer }}
    - run: dotnet nuget push "**/bin/Release/*.nupkg" -k ${{ secrets.NUGET_API_KEY }}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    - uses: actions/github-script@v6
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/v${{ steps.gitversion.outputs.fullSemVer }}',
            sha: context.sha
          })
